[versions]
# Plugin versions
agp = "8.13.2"
kotlin = "2.3.0"

# AndroidX Libraries
coreKtx = "1.17.0"
appcompat = "1.7.1"

# UI components
material = "1.13.0"
mockitoInline = "5.2.0"
recyclerview = "1.4.0"
coordinatorlayout = "1.3.0"

# Testing
junit = "4.13.2"
testRules = "1.6.1"
testCore = "1.7.0"
testRunner = "1.7.0"
testExtJunit = "1.3.0"
mockito = "5.21.0"
mockitoKotlinVersion = "6.2.1"
espresso = "3.7.0"
mockkVersion = "1.13.13"
robolectric = "4.16"
constraintlayout = "2.2.1"

[libraries]
# AndroidX Libraries
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

# UI components
androidx-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "espresso" }
androidx-espresso-idling-resource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "espresso" }
core-ktx = { module = "androidx.test:core-ktx", version.ref = "testCore" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version.ref = "coordinatorlayout" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
#androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "testRules" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "testCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "testRunner" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "testExtJunit" }

mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-android = { group = "org.mockito", name = "mockito-android", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockitoKotlinVersion" }
#mock-io = { group = "io.mockk", name = "mockk", version.ref = "mockkVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }

robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
# Core
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
